### ISSUE TITLE
Items won't work in full width after install.

### ISSUE THREAD

**Issue by dwangove** [hendrikreimers/content_effects#1]
Content Elements like header images and carousels are framed after install instead of being full width.
Disabling the extension reverts it back to normal.

**Comment by dwangove** [comment]
It appears to be placing a frame around elements even when there are no effects applied to them.
This is just with the bootstrap/intro package installed.  I haven't loaded any additional extensions beyond content_effects 1.0.3

**Comment by hendrikreimers** [comment]
Thank you for your issue. It sound a little bit mysterious, because this Extension isn't wrapping anything. It just uses a DataProcessor to extend the Data Array of the content element. Everything else is done by default TYPO3 Fluid Styled Content Extension or others.

Take a look at this: [https://github.com/hendrikreimers/content_effects/blob/master/Configuration/TypoScript/setup.typoscript](url)

and this:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Resources/Private/Layouts/Default.html

It extends the frame_class variable which is used inside the Fluid Style Content Template.

Maybe in your case, something changed the defaults in the intro package, which is overriding the layout to exclude the frame wrapping. 

In your case i recommend to exclude the dataProcessor for the special content elements like header image or else. You need to identify the CType name of this elements and could exclude it for example like this over typoscript setup:

`tt_content.myCTypeElement.dataProcessing.5 >`

**Comment by dwangove** [comment]
Thanks for your response!  I will look at your options. I’m new to typo3, and just starting to get into the guts of it.

 

For reference, here is the difference, code wise, with or without content_effects (the highlighted showing what is added):

 

# with content_effects

<div class="frame frame-none  frame-type-carousel frame-layout-0 frame-background-none frame-no-backgroundimage frame-space-before-none frame-space-after-none" id="c212">

    <div class="frame-container">

        <div class="frame-inner">

            <div class="carousel carousel-fade slide" id="carousel-212" style="-ms-content-zooming: none; -ms-user-select: none; -ms-touch-select: none; touch-action: pan-y; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" data-ride="carousel" data-wrap="true" data-interval="5000">

                <div class="carousel-inner">

                    <div class="item active carousel-item carousel-item-type carousel-item-type-header" style="background-color: #333333;" data-itemno="0">

                        <div class="carousel-backgroundimage-container">

                            <div class="carousel-backgroundimage carousel-backgroundimage-parallax carousel-backgroundimage-fade carousel-backgroundimage-grayscale" id="carousel-backgroundimage-212-9"><style>#carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_9f9252ffa5.jpg'); } @media (min-width: 576px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_3990d1f415.jpg'); }} @media (min-width: 768px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_8a22658ce3.jpg'); }} @media (min-width: 992px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_32740f1fec.jpg'); }} @media (min-width: 1200px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_daceb50a1d.jpg'); }} </style>

                            </div>

                        </div>

                        <div class="carousel-content">

                            <div class="valign" style="color: #FFFFFF;">

                                <div class="vcontainer">

                                    <div class="carousel-text-inner"><h1 class="carousel-header text-center awesome h2">Open source, enterprise CMS delivering  content-rich digital experiences on any channel,  any device, in any language</h1>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

 

# without content_effects

<div class="carousel carousel-fade slide" id="carousel-212" style="-ms-content-zooming: none; -ms-user-select: none; -ms-touch-select: none; touch-action: pan-y; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" data-ride="carousel" data-wrap="true" data-interval="5000">

    <div class="carousel-inner">

        <div class="item active carousel-item carousel-item-type carousel-item-type-header" style="background-color: #333333;" data-itemno="0">

            <div class="carousel-backgroundimage-container">

                <div class="carousel-backgroundimage carousel-backgroundimage-parallax carousel-backgroundimage-fade carousel-backgroundimage-grayscale" id="carousel-backgroundimage-212-9">

                <style>#carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_de0b1150dc.jpg'); } @media (min-width: 576px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_c985ca1c5e.jpg'); }} @media (min-width: 768px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_a2c1f87f47.jpg'); }} @media (min-width: 992px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_b57eb5a31c.jpg'); }} @media (min-width: 1200px) { #carousel-backgroundimage-212-9 { background-image: url('/typo3/fileadmin/_processed_/4/6/csm_the-creative-exchange-373981-unsplash_e777eb6883.jpg'); }} </style>

                </div>

            </div>

            <div class="carousel-content">

                <div class="valign" style="color: #FFFFFF;">

                    <div class="vcontainer">

                        <div class="carousel-text-inner"><h1 class="carousel-header text-center awesome h2">Open source, enterprise CMS delivering  content-rich digital experiences on any channel, any device, in any language</h1>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

**Comment by dwangove** [comment]
Additional info: this was a clean install with only the preloader in the bootstrap package disabled.

**Comment by hendrikreimers** [comment]
No problem, we all started learning TYPO3 at some point.
As expected and written before, the Bootstrap Introduction package overwrites the Fluid Styled Content Layout and looks, whether a frame_class variable is set. This is why your content elements gots wrapped.

See it here on line 18:
[https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Layouts/ContentElements/Default.html](url)

`    <f:if condition="{data.frame_class} != none">
<f:then>`

This is not a bug in the content_effects, it's an additional usage handling for content elements by the Introduction Package.

If you want to finde out, which CType you want to exclude, you need to take a look at the page TSconfig of the Introduction package here:

[https://github.com/benjaminkott/bootstrap_package/tree/master/Configuration/TsConfig/Page/ContentElement/Element](url)

For example take a look at the **CarouselFullscreen.typoscript** at line **6**. This is the CType name:
_carousel_fullscreen_

If you want to exclude it from wrapping write in your own TypoScript Setup (for example over the Template module) the following:

`tt_content.carousel_fullscreen.dataProcessing.5 >`

and after that it should not wrapped anymore.
